const utilityClass = [
  "flex gap-1",
  "flex gap-2",
  "flex gap-3",
  "flex gap-4",
  "flex gap-5",
  "flex gap-6",
  "flex gap-7",
  "flex gap-8",
  "flex gap-9",
  "flex gap-10",
  "flex gap-11",
  "flex gap-12",
  "flex gap-13",
  "flex gap-14",
  "flex gap-15",
  "flex gap-16",
  "flex gap-17",
  "flex gap-18",
  "flex gap-19",
  "flex gap-20",
  "flex gap-21",
  "flex gap-22",
  "flex gap-23",
  "flex gap-24",
  "flex gap-25",
  "flex gap-26",
  "flex gap-27",
  "flex gap-28",
  "flex gap-29",
  "flex gap-30",
  "flex gap-31",
  "flex gap-32",
  "flex gap-33",
  "flex gap-34",
  "flex gap-35",
  "flex gap-36",
  "flex gap-37",
  "flex gap-38",
  "flex gap-39",
  "flex gap-40",
  "flex gap-41",
  "flex gap-42",
  "flex gap-43",
  "flex gap-44",
  "flex gap-45",
  "flex gap-46",
  "flex gap-47",
  "flex gap-48",
  "flex gap-49",
  "flex gap-50",
  "flex gap-60",
  "flex gap-70",
  "flex gap-80",
  "flex gap-90",
  "flex gap-100",
  "flex gap-110",
  "flex gap-120",
  "flex gap-130",
  "flex gap-140",
  "flex gap-150",
  "flex gap-160",
  "flex gap-170",
  "flex gap-180",
  "flex gap-190",
  "flex gap-200",
  "flex gap-210",
  "flex gap-220",
  "flex gap-230",
  "flex gap-240",
  "flex gap-250",
  "flex gap-260",
  "flex gap-270",
  "flex gap-280",
  "flex gap-290",
  "flex gap-300",
  "container-center",
  "divider",
  "badge-success",
  "badge-danger",
  "badge-warning",
  "badge-secondary",
  "badge-primary",
  "badge-defalut",
  "sm-1",
  "sm-2",
  "btn-success",
  "btn-danger",
  "btn-warning",
  "btn-secondary",
  "btn-primary",
  "btn-defalut",
  "color-red-50",
  "color-red-100",
  "color-red-200",
  "color-red-300",
  "color-red-400",
  "color-red-500",
  "color-red-600",
  "color-red-700",
  "color-red-800",
  "color-red-900",
  "color-blue-50",
  "color-blue-100",
  "color-blue-200",
  "color-blue-300",
  "color-blue-400",
  "color-blue-500",
  "color-blue-600",
  "color-blue-700",
  "color-blue-800",
  "color-blue-900",
  "color-green-50",
  "color-green-100",
  "color-green-200",
  "color-green-300",
  "color-green-400",
  "color-green-500",
  "color-green-600",
  "color-green-700",
  "color-green-800",
  "color-green-900",
  "color-yellow-50",
  "color-yellow-100",
  "color-yellow-200",
  "color-yellow-300",
  "color-yellow-400",
  "color-yellow-500",
  "color-yellow-600",
  "color-yellow-700",
  "color-yellow-800",
  "color-yellow-900",
  "color-gray-50",
  "color-gray-100",
  "color-gray-200",
  "color-gray-300",
  "color-gray-400",
  "color-gray-500",
  "color-gray-600",
  "color-gray-700",
  "color-gray-800",
  "color-gray-900",
  "color-purple-50",
  "color-purple-100",
  "color-purple-200",
  "color-purple-300",
  "color-purple-400",
  "color-purple-500",
  "color-purple-600",
  "color-purple-700",
  "color-purple-800",
  "color-purple-900",
  "color-pink-50",
  "color-pink-100",
  "color-pink-200",
  "color-pink-300",
  "color-pink-400",
  "color-pink-500",
  "color-pink-600",
  "color-pink-700",
  "color-pink-800",
  "color-pink-900",
  "color-orange-50",
  "color-orange-100",
  "color-orange-200",
  "color-orange-300",
  "color-orange-400",
  "color-orange-500",
  "color-orange-600",
  "color-orange-700",
  "color-orange-800",
  "color-orange-900",
  "color-teal-50",
  "color-teal-100",
  "color-teal-200",
  "color-teal-300",
  "color-teal-400",
  "color-teal-500",
  "color-teal-600",
  "color-teal-700",
  "color-teal-800",
  "color-teal-900",
  "color-gradient-red-yellow",
  "color-gradient-blue-green",
  "color-gradient-purple-pink",
  "color-gradient-orange-red",
  "color-gradient-teal-cyan",
  "color-gradient-gray-black",
  "color-gradient-gold-orange",
  "color-gradient-pink-blue",
  "color-gradient-lime-green",
  "color-gradient-red-violet",
  "color-gradient-radial-red",
  "color-gradient-radial-blue",
  "color-gradient-radial-green",
  "color-gradient-radial-purple",
  "color-gradient-radial-orange",
  "color-gradient-radial-gray",
  "color-gradient-radial-pink",
  "color-gradient-radial-cyan",
  "color-gradient-radial-yellow",
  "color-gradient-radial-brown",
  "color-gradient-coral-aqua",
  "color-gradient-indigo-gold",
  "color-gradient-salmon-plum",
  "color-gradient-teal-orange",
  "color-gradient-mint-peach",
  "color-gradient-maroon-olive",
  "color-gradient-dark-cyan-light-cyan",
  "color-gradient-light-dark-gray",
  "color-gradient-lavender-rose",
  "color-gradient-light-pink-blue",
  "color-gradient-radial-navy-sky",
  "color-gradient-radial-sunset-twilight",
  "color-gradient-radial-forest-light-green",
  "color-gradient-radial-light-coral-deep-pink",
  "color-gradient-radial-deep-sky-royal",
  "color-gradient-radial-dark-olive-pale",
  "color-gradient-radial-light-steel-midnight",
  "color-gradient-radial-gold-silver",
  "color-gradient-radial-hotpink-electric",
  "color-gradient-radial-tomato-violet",
  "background-color-red-50",
  "background-color-red-100",
  "background-color-red-200",
  "background-color-red-300",
  "background-color-red-400",
  "background-color-red-500",
  "background-color-red-600",
  "background-color-red-700",
  "background-color-red-800",
  "background-color-red-900",
  "background-color-blue-50",
  "background-color-blue-100",
  "background-color-blue-200",
  "background-color-blue-300",
  "background-color-blue-400",
  "background-color-blue-500",
  "background-color-blue-600",
  "background-color-blue-700",
  "background-color-blue-800",
  "background-color-blue-900",
  "background-color-green-50",
  "background-color-green-100",
  "background-color-green-200",
  "background-color-green-300",
  "background-color-green-400",
  "background-color-green-500",
  "background-color-green-600",
  "background-color-green-700",
  "background-color-green-800",
  "background-color-green-900",
  "background-color-yellow-50",
  "background-color-yellow-100",
  "background-color-yellow-200",
  "background-color-yellow-300",
  "background-color-yellow-400",
  "background-color-yellow-500",
  "background-color-yellow-600",
  "background-color-yellow-700",
  "background-color-yellow-800",
  "background-color-yellow-900",
  "background-color-gray-50",
  "background-color-gray-100",
  "background-color-gray-200",
  "background-color-gray-300",
  "background-color-gray-400",
  "background-color-gray-500",
  "background-color-gray-600",
  "background-color-gray-700",
  "background-color-gray-800",
  "background-color-gray-900",
  "background-color-gradient-red-yellow",
  "background-color-gradient-blue-green",
  "background-color-gradient-purple-pink",
  "background-color-gradient-orange-red",
  "background-color-gradient-teal-cyan",
  "background-color-gradient-gray-black",
  "background-color-gradient-radial-red",
  "background-color-gradient-radial-blue",
  "background-color-gradient-radial-green",
  "background-color-gradient-radial-purple",
  "background-color-gradient-radial-orange",
  "background-color-gradient-radial-gray",
];

module.exports = utilityClass;
